#!groovy

library 'kentrikos-shared-library'
pipeline {
    agent any
    stages {
        stage('Git clone') {
            steps {
                cleanWs()
                git url: 'https://github.com/kentrikos/jenkins-x-image.git'
            }
        }
        stage('Build') {
            steps {
                withProxyEnv() {
                    sh 'docker build -t jenkins-x-kentrikos  .'
                }
            }
        }
        stage('Tag') {
            steps {
                withProxyEnv() {
                    sh 'docker tag jenkins-x-kentrikos $AWS_OPERATIONS_ACCOUNT_NUMBER.dkr.ecr.$AWS_REGION.amazonaws.com/${PRODUCT_DOMAIN_NAME}-${ENVIRONMENT_TYPE}-jenkins-x-image'

                }
            }
        }
        stage('Push') {
            steps {
                withProxyEnv() {
                    sh 'eval $(aws ecr get-login --no-include-email --region $AWS_REGION | sed "s|https://||")'
                    sh 'docker push  $AWS_OPERATIONS_ACCOUNT_NUMBER.dkr.ecr.$AWS_REGION.amazonaws.com/${PRODUCT_DOMAIN_NAME}-${ENVIRONMENT_TYPE}-jenkins-x-image'
                }
            }
        }
    }
}
