#!groovy

library 'kentrikos-shared-library'
pipeline {

    agent any

    parameters {
        choice(name: 'K8S_FLAVOR', choices: ["eks", "kops"],
                description: 'Choose type of Kubernetes cluster (required for kops)')
    }

    environment {
        OPERATION_OPS_DIR = "operations/$AWS_REGION/env-$K8S_FLAVOR"
        OPERATION_APP_DIR = "application/$AWS_REGION/env-$K8S_FLAVOR"

    }
    stages {
        stage('Git clone') {
            steps {
                gitCloneConfigRepo()
            }
        }

        stage('Switch K8S context') {
            steps {
                kubectlSwitchContextApp()
            }
        }

        stage('Destroy Prometheus/app') {
            steps {
                dir("$OPERATION_APP_DIR") {
                    withProxyEnv() {
                        withAWS(role: "$CROSS_ACCOUNT_ROLE_NAME", roleAccount: "$AWS_APPLICATION_ACCOUNT_NUMBER") {
                            script {
                                sh 'helm delete --purge prometheus-app'
                            }
                        }
                    }
                }
            }
        }

        stage('Read Grafana endpoint') {
            steps {
                dir("$OPERATION_OPS_DIR") {
                    withProxyEnv() {
                        script {
                            def jenkinsParameters = readYaml file: 'jenkins/parameters.yaml'
                            def grafanaParameters = readYaml file: 'grafana/parameters.yaml'

                            println "Getting domain name"
                            def r53DomainName = sh(script: "aws route53 get-hosted-zone --id " + jenkinsParameters.domainHostedZoneID + " --output text --query 'HostedZone.Name'",
                                    returnStdout: true).trim().replaceAll("\\.\$", "")
                            grafanaEndpoint = "grafana." + jenkinsParameters.domainAliasPrefix + "." + r53DomainName
                            grafanaAdminPassword = grafanaParameters.defaultAdminPassword
                        }
                    }
                }
            }
        }

        stage('Destroy Prometheus_app data-source in Grafana') {
            steps {
                dir("$OPERATION_OPS_DIR") {
                    withProxyEnv() {
                        script {
                            def prometheusDataSourceName = "Prometheus_app"
                            sh "curl --verbose --user admin:${grafanaAdminPassword} http://${grafanaEndpoint}/api/datasources/name/${prometheusDataSourceName} -X DELETE -H 'Content-Type: application/json;charset=UTF-8'"
                        }
                    }
                }
            }
        }

        stage('Delete Prometheus/app dashboard from Grafana') {
            steps {
                dir("$OPERATION_OPS_DIR") {
                    withProxyEnv() {
                        script {
                            def grafanaDashboardUID = "kcapp"
                            sh "curl --verbose --user admin:${grafanaAdminPassword} http://${grafanaEndpoint}/api/dashboards/uid/${grafanaDashboardUID} -X DELETE -H 'Content-Type: application/json;charset=UTF-8'"
                        }
                    }
                }
            }
        }
    }
}
