#!groovy

import groovy.json.JsonOutput

library 'kentrikos-shared-library'
def helmRbacConfig = '''
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: tiller
    namespace: kube-system
'''
def ingValue = '''
rbac:
 create: true

controller:
 service:
   annotations:
     service.beta.kubernetes.io/aws-load-balancer-type: nlb
     service.beta.kubernetes.io/aws-load-balancer-internal: true
   enableHttp: true
   enableHttps: false
'''
def jxValueMap = [
        jenkins: [
                Master : [
                        Image           : env.AWS_OPERATIONS_ACCOUNT_NUMBER + ".dkr.ecr." + env.AWS_REGION + ".amazonaws.com/" + env.PRODUCT_DOMAIN_NAME + "-" + env.ENVIRONMENT_TYPE + "-jenkins-x-image",
                        ImageTag        : "latest",
                        InitContainerEnv: [],
                        ContainerEnv    : []
                ],
                Servers: [
                        Global: [
                                NumEnvVars: 8,
                                EnvVars   : [
                                        CONFIG_REPO_URL               : env.CONFIG_REPO_URL,
                                        JOB_REPO_URL                  : env.JOB_REPO_URL,
                                        AWS_REGION                    : env.AWS_REGION,
                                        AWS_OPERATIONS_ACCOUNT_NUMBER : env.AWS_OPERATIONS_ACCOUNT_NUMBER,
                                        AWS_APPLICATION_ACCOUNT_NUMBER: env.AWS_APPLICATION_ACCOUNT_NUMBER,
                                        PRODUCT_DOMAIN_NAME           : env.PRODUCT_DOMAIN_NAME,
                                        ENVIRONMENT_TYPE              : env.ENVIRONMENT_TYPE,

                                ]
                        ]
                ]
        ]
]

pipeline {
    environment {
        ENV_K8S_DIR = 'env-kops'
        OPERTION_DIR = "operations/$AWS_REGION/$ENV_K8S_DIR"
    }
    agent any
    stages {
        stage('Git clone') {
            steps {
                gitCloneConfigRepo()
            }
        }
        stage('Init helm') {
            steps {
                dir("$OPERTION_DIR") {
                    withProxyEnv() {
                        writeFile file: 'helm-rbac-config.yaml', text: helmRbacConfig
                        sh 'kubectl create -f helm-rbac-config.yaml ||true'
                        sh 'helm init --service-account tiller --wait --upgrade --tiller-connection-timeout 600'
                    }
                }
            }
        }
        stage('Init k8s ingress') {
            steps {
                dir("$OPERTION_DIR") {
                    withProxyEnv() {
                        writeFile file: 'ing-values.yaml', text: ingValue
                        sh 'helm install --replace --wait --name jxing --namespace kube-system stable/nginx-ingress --set rbac.create=true --values ing-values.yaml||true'
                    }
                }
            }
        }
        stage('Create wildcard DNS record') {
            steps {
                dir("$OPERTION_DIR") {
                    withProxyEnv() {
                        script {
                            def parameters = readYaml file: 'jenkins/parameters.yaml'

                            println "Getting domain name"
                            def r53DomainName = sh(script: "aws route53 get-hosted-zone --id " + parameters.jxDomainHostedZoneID + " --output text --query 'HostedZone.Name'",
                                    returnStdout: true).trim().replaceAll("\\.\$", "")
                            r53WildcardRecordName = "*." + parameters.jxDomainAliasPrefix + "." + r53DomainName

                            println "Getting ingress NLB information"
                            ingressNLBAddress = sh(script: "kubectl get service -n kube-system jxing-nginx-ingress-controller -o json | jq -r '.status.loadBalancer.ingress[0].hostname'",
                                    returnStdout: true).trim()
                            ingressNLBHostedZoneID = sh(script: "aws --region \$AWS_REGION elbv2 describe-load-balancers --query 'LoadBalancers[?DNSName==`" + ingressNLBAddress + "`].CanonicalHostedZoneId' --output text",
                                    returnStdout: true).trim()

                            println "Generating record for DNS update"
                            def r53WildcardRecordJSON = """
                            {
                                "Comment": "Creating Alias resource record sets in Route 53",
                                "Changes": [{
                                    "Action": "UPSERT",
                                    "ResourceRecordSet": {
                                        "Name": "${r53WildcardRecordName}",
                                        "Type": "A",
                                        "AliasTarget": {
                                            "HostedZoneId": "${ingressNLBHostedZoneID}",
                                            "DNSName": "${ingressNLBAddress}",
                                            "EvaluateTargetHealth": false
                                        }
                                    }
                                }]
                            }
                            """
                            writeFile file: 'jx_r53_alias.json', text: r53WildcardRecordJSON
                            sh "cat jx_r53_alias.json"

                            println "Creating/updating Route53 entry"
                            sh "aws route53 change-resource-record-sets --hosted-zone-id " + parameters.jxDomainHostedZoneID + " --change-batch file://jx_r53_alias.json"
                        }
                    }
                }
            }
        }
        stage('Install jx on k8s') {
            steps {
                dir("$OPERTION_DIR") {
                    ansiColor('xterm') {
                        withProxyEnv() {
                            script {
                                def parameters = readYaml file: 'jenkins/parameters.yaml'

                                println "Getting domain name"
                                def r53DomainName = sh(script: "aws route53 get-hosted-zone --id " + parameters.jxDomainHostedZoneID + " --output text --query 'HostedZone.Name'",
                                        returnStdout: true).trim().replaceAll("\\.\$", "")

                                URI url_http_proxy = new URI(env.http_proxy)
                                URI url_https_proxy = new URI(env.https_proxy)
                                def jenkins_no_proxy = env.no_proxy.toString()
                                jxValueMap.jenkins.Master.InitContainerEnv = [[name: 'http_proxy', value: env.http_proxy], [name: 'https_proxy', value: env.http_proxy], [name: 'no_proxy', value: env.no_proxy], [name: 'jenkins_proxy_http', value: url_http_proxy?.getHost()], [name: 'jenkins_proxy_http_port', value: url_http_proxy?.getPort().toString()], [name: 'jenkins_no_proxy_list', value: jenkins_no_proxy.split(',').join('\\n')], [name: 'JOB_REPO_URL', value: env.JOB_REPO_URL]]
                                jxValueMap.jenkins.Master.ContainerEnv = [[name: 'http_proxy', value: env.http_proxy], [name: 'https_proxy', value: env.http_proxy], [name: 'no_proxy', value: env.no_proxy], [name: 'jenkins_proxy_http', value: url_http_proxy?.getHost()], [name: 'jenkins_proxy_http_port', value: url_http_proxy?.getPort().toString()], [name: 'jenkins_no_proxy_list', value: jenkins_no_proxy.split(',').join('\\n')], [name: 'JOB_REPO_URL', value: env.JOB_REPO_URL]]
                                jxValueMap.jenkins.Master.JavaOpts = '-Dhudson.slaves.NodeProvisioner.initialDelay=0 -Dhudson.slaves.NodeProvisioner.MARGIN=50 -Dhudson.slaves.NodeProvisioner.MARGIN0=0.85 -Djenkins.displayurl.provider=org.jenkinsci.plugins.blueoceandisplayurl.BlueOceanDisplayURLImpl -Dhttp.proxyHost=' + url_http_proxy?.getHost() + ' -Dhttp.proxyPort=' + url_http_proxy?.getPort()
                                writeYaml file: 'myvalues.yaml', data: jxValueMap

                                sh 'sed -r -i \'s/value: ([^ \'\\\'\']+)/value: "\\1"/g\' myvalues.yaml'

                                sh 'jx install -b --headless --default-admin-password ' + parameters.defaultAdminPassword + ' --domain="' + parameters.jxDomainAliasPrefix + "." + r53DomainName + '" --verbose=true --provider=kubernetes --no-default-environments --git-username=' + parameters.gitUsername + ' --git-api-token ' + parameters.gitApiToken + ' --git-provider-url="' + parameters.gitProviderUrl + '"'
                            }
                        }
                    }
                }
            }
        }
    }
}