#!groovy

library 'kentrikos-shared-library'
pipeline {
    agent any
    environment {
        SUBCOMPONENT_DIR = 'vpc_endpoint_service_k8s'
        OPERATION_DIR    = "application/$AWS_REGION/$SUBCOMPONENT_DIR"
    }
    parameters {
        choice(name: 'K8S_FLAVOR', choices: ["eks", "kops"],
               description: 'Choose type of Kubernetes cluster (required for kops)')
    }
    stages {
        stage('Git clone') {
            steps {
                gitCloneConfigRepo()
            }
        }
        stage('Init') {
            steps {
                terraformInitApplication dir: "$OPERATION_DIR", subcomponent: "${SUBCOMPONENT_DIR}", withAWS: true
            }
        }
        stage('Plan') {
            script {
              steps {
                  terraformPlanDestroy dir: "$OPERATION_DIR", extraArgs: "-var=\"cluster_type=${K8S_FLAVOR}\"", withAWS: true
              }
            }
        }
        stage('Apply') {
            input {
                message "Should we continue?"
                ok "Yes, we should."
            }
            steps {
                terraformApplyDestroy dir: "$OPERATION_DIR", withAWS: true
            }
        }
    }
}
