#!groovy

library 'kentrikos-shared-library'
pipeline {
    agent any
    environment {
        SUBCOMPONENT_DIR = 'vpc_endpoint_service_k8s'
        OPERATION_DIR    = "application/$AWS_REGION/$SUBCOMPONENT_DIR"
    }
    stages {
        stage('Git clone') {
            steps {
                gitCloneConfigRepo()
            }
        }
        stage('Init') {
            steps {
                terraformInitApplication dir: "$OPERATION_DIR", subcomponent: "${SUBCOMPONENT_DIR}", withAWS: true
            }
        }
        stage('Plan') {
            steps {
                terraformPlanDestroy dir: "$OPERATION_DIR", withAWS: true
            }
        }
        stage('Apply') {
            input {
                message "Should we continue?"
                ok "Yes, we should."
            }
            steps {
                terraformApplyDestroy dir: "$OPERATION_DIR", withAWS: true
            }
        }
    }
}
