#!groovy

library 'kentrikos-shared-library'
pipeline {

    environment {
        OPERATION_DIR = "application/$AWS_REGION/iam/auto"
        SUBCOMPONENT = "iam"
    }
    agent any
    stages {
        stage('Git clone') {
            steps {
                gitCloneConfigRepo()
            }
        }
        stage('Init') {
            steps {
                terraformInitApplication dir: "$OPERATION_DIR", subcomponent: "$SUBCOMPONENT", withAWS: false
            }
        }
        stage('Plan') {
            steps {
                terraformPlan dir: "$OPERATION_DIR"
            }
        }
        stage('Apply') {
            input {
                message "Should we continue?"
                ok "Yes, we should."
            }
            steps {
                terraformApply dir: "$OPERATION_DIR"
            }
        }
    }
}

