#!groovy

library 'kentrikos-shared-library'

pipeline {
    options {
        timeout(time: 60, unit: 'MINUTES')
    }
    environment {
        ENV_K8S_DIR = 'env-kops'
        OPERTION_DIR = "operations/$AWS_REGION/$ENV_K8S_DIR"
    }
    agent any
    stages {
        stage('Git clone') {
            steps {
                gitCloneConfigRepo()
            }
        }
        stage('Init') {
            steps {
                terraformInitOperations dir: "$OPERTION_DIR", subcomponent: "${ENV_K8S_DIR}"
            }
        }
        stage('Plan') {
            steps {
                terraformPlan dir: "$OPERTION_DIR"
            }
        }
        stage('Apply') {
            input {
                message "Should we continue?"
                ok "Yes, we should."
            }
            steps {
                terraformApply dir: "$OPERTION_DIR"
            }
        }
    }
}
