#!groovy

import groovy.json.JsonOutput

library 'kentrikos-shared-library'
pipeline {

    agent any

    parameters {
        choice(name: 'K8S_FLAVOR', choices: ["eks", "kops"],
                description: 'Choose type of Kubernetes cluster (required for kops)')
    }
    environment {
        OPERATION_DIR = "operations/$AWS_REGION/logging"
        SUB_COMPONENT = "logging"
    }
    stages {
        stage('Git clone') {
            steps {
                gitCloneConfigRepo()
            }
        }
        stage('Switch K8S context') {
            steps {
                steps {
                    kubectlSwitchContextOps()
                }
            }
        }
        stage('Init') {
            steps {
                terraformInitOperations dir: "$OPERATION_DIR", subcomponent: "$SUB_COMPONENT"
            }
        }
        stage('Plan') {
            steps {
                script {
                    K8S_CLUSTER_NAME = sh(script: "kubectl config current-context", returnStdout: true).trim()
                    terraformPlanDestroy dir: "$OPERATION_DIR", extraArgs: "-var=\"cluster_context=${K8S_CLUSTER_NAME}\""
                }
            }
        }
        stage('Apply') {
            input {
                message "Should we continue?"
                ok "Yes, we should."
            }
            steps {
                terraformApplyDestroy dir: "$OPERATION_DIR"
            }
        }
    }
}