#!groovy
library 'kentrikos-shared-library'
pipeline {
    environment {
        OPERTION_DIR = "operations/$AWS_REGION/iam"
        SUBCOMPONENT = "iam"
    }
    agent any
    stages {
        stage('Git clone') {
            steps {
                gitCloneConfigRepo()
            }
        }
        stage('Init') {
            steps {
                terraformInitOperations dir: "$OPERTION_DIR", subcomponent: "$SUBCOMPONENT"
            }
        }
        stage('Plan') {
            steps {
                terraformPlan dir: "$OPERTION_DIR"
            }
        }
        stage('Apply') {
            input {
                message "Should we continue?"
                ok "Yes, we should."
            }
            steps {
                terraformApply dir: "$OPERTION_DIR"
            }
        }
    }
}
