#!groovy

library 'kentrikos-shared-library'
pipeline {
    options {
        timeout(time: 60, unit: 'MINUTES')
    }
    environment {
        ENV_K8S_DIR = 'env-eks'
        OPERATION_DIR = "operations/$AWS_REGION/$ENV_K8S_DIR"
    }
    agent any
    stages {
        stage('Git clone') {
            steps {
                gitCloneConfigRepo()
            }
        }
        stage('Init') {
            steps {
                terraformInitOperations dir: "$OPERATION_DIR", subcomponent: "${ENV_K8S_DIR}"
            }
        }
        stage('Plan') {
            steps {
                terraformPlan dir: "$OPERATION_DIR"
            }
        }
        stage('Apply') {
            input {
                message "Should we continue?"
                ok "Yes, we should."
            }
            steps {
                terraformApply dir: "$OPERATION_DIR"
            }
        }
        stage('Retrieve kubeconfig') {
            steps {
                withProxyEnv() {
                    sh '''#!/bin/bash -x
                       aws eks update-kubeconfig --name ${AWS_REGION}-${PRODUCT_DOMAIN_NAME}-${ENVIRONMENT_TYPE}-ops --region ${AWS_REGION}
                       '''
                }
            }
        }
    }
}
