#!groovy

library 'kentrikos-shared-library'
pipeline {
    options {
        timeout(time: 60, unit: 'MINUTES')
    }
    parameters {
        choice(name: 'K8S_FLAVOR', choices: ["eks", "kops"],
                description: 'Choose type of Kubernetes cluster (required for kops)')
    }
    environment {
        SUBCOMPONENT_DIR = 'vpc-endpoint-to-vpces'
        OPERATION_DIR = "operations/$AWS_REGION/$SUBCOMPONENT_DIR"
    }
    agent any
    stages {
        stage('Git clone') {
            steps {
                gitCloneConfigRepo()
            }
        }
        stage('Init') {
            steps {
                terraformInitOperations dir: "$OPERATION_DIR", subcomponent: "${SUBCOMPONENT_DIR}"
            }
        }
        stage('Plan') {
            steps {
                script {
                    terraformPlan dir: "$OPERATION_DIR"
                }
            }
        }
        stage('Apply') {
            input {
                message "Should we continue?"
                ok "Yes, we should."
            }
            steps {
                terraformApply dir: "$OPERATION_DIR"
            }
        }
    }
}
