#!groovy

library 'kentrikos-shared-library'
pipeline {
    agent any
    environment {
        ENV_K8S_DIR = 'env-eks'
        OPERATION_DIR = "application/$AWS_REGION/$ENV_K8S_DIR"
    }
    stages {
        stage('Git clone') {
            steps {
                gitCloneConfigRepo()
            }
        }
        stage('Init') {
            steps {
                terraformInitApplication dir: "$OPERATION_DIR", subcomponent: "${ENV_K8S_DIR}", withAWS: true
            }
        }
        stage('Plan') {
            steps {
                terraformPlanDestroy dir: "$OPERATION_DIR", withAWS: true
            }
        }
        stage('Apply') {
            input {
                message "Should we continue?"
                ok "Yes, we should."
            }
            steps {
                terraformDestroy dir: "$OPERATION_DIR", withAWS: true
            }
        }
    }
}
